import '../model/history_model.dart';
import '../model/image_model.dart';

class HistoryData {
  static final List<HistoryModel> historyModelList = [
    HistoryModel(
      farmName: 'Fazenda de Soja',
      farmId: '1',
      culture: 'Soja',
      initialPests: ['Lagartas', 'Fungos', 'Bactérias'],
      initialDiseases: ['Vírus'],
      initialIrrigation: true,
      progressHistory: [
        'Aplicação de inseticidas para controle de lagartas - Pragas reduzidas',
        'Aplicação de fungicidas para controle de fungos - Fungos reduzidos',
        'Monitoramento contínuo das bactérias - Bactérias sob controle',
        'Implementação de medidas preventivas para evitar a propagação de vírus - Doenças controladas',
        'Manutenção regular do sistema de irrigação - Irrigação estável',
      ],
      imageUrl: 'assets/images/plantacao_soja.jpg',
    ),
    HistoryModel(
      farmName: 'Fazenda de Milho',
      farmId: '2',
      culture: 'Milho',
      initialPests: ['Ácaros', 'Fungos', 'Bactérias'],
      initialDiseases: ['Vírus', 'Bactérias'],
      initialIrrigation: true,
      progressHistory: [
        'Uso de acaricidas para controle de ácaros - Pragas reduzidas',
        'Aplicação de fungicidas para controle de fungos - Fungos controlados',
        'Tratamento bactericida para combater as bactérias - Bactérias sob controle',
        'Implementação de estratégias de manejo integrado para controle de vírus - Doenças controladas',
        'Verificação e manutenção regular do sistema de irrigação - Irrigação estável',
      ],
      imageUrl: 'assets/images/plantacao_milho.jpg',
    ),
    HistoryModel(
      farmName: 'Fazenda de Trigo',
      farmId: '3',
      culture: 'Trigo',
      initialPests: ['Gafanhotos', 'Fungos'],
      initialDiseases: ['Bactérias'],
      initialIrrigation: false,
      progressHistory: [
        'Aplicação de inseticidas para controle de gafanhotos - Pragas reduzidas',
        'Aplicação de fungicidas para controle de fungos - Fungos controlados',
        'Monitoramento contínuo das bactérias - Bactérias sob controle',
      ],
      imageUrl: 'assets/images/plantacao_trigo.jpg',
    ),
    HistoryModel(
      farmName: 'Fazenda de Algodão',
      farmId: '4',
      culture: 'Algodão',
      initialPests: ['Cupins', 'Fungos'],
      initialDiseases: ['Vírus', 'Bactérias'],
      initialIrrigation: true,
      progressHistory: [
        'Uso de cupinicidas para controle de cupins - Pragas reduzidas',
        'Aplicação de fungicidas para controle de fungos - Fungos reduzidos',
        'Tratamento antiviral para combater os vírus - Doenças controladas',
        'Tratamento bactericida para combater as bactérias - Bactérias sob controle',
        'Verificação e manutenção regular do sistema de irrigação - Irrigação estável',
      ],
      imageUrl: 'assets/images/plantacao_algodao.jpg',
    ),
    HistoryModel(
      farmName: 'Fazenda de Arroz',
      farmId: '5',
      culture: 'Arroz',
      initialPests: ['Lagartas', 'Ácaros'],
      initialDiseases: ['Fungos'],
      initialIrrigation: true,
      progressHistory: [
        'Aplicação de inseticidas para controle de lagartas - Pragas reduzidas',
        'Uso de acaricidas para controle de ácaros - Pragas controladas',
        'Aplicação de fungicidas para controle de fungos - Fungos reduzidos',
        'Verificação e manutenção regular do sistema de irrigação - Irrigação estável',
      ],
      imageUrl: 'assets/images/plantacao_arroz.jpg',
    ),
    HistoryModel(
      farmName: 'Fazenda de Feijão',
      farmId: '6',
      culture: 'Feijão',
      initialPests: ['Cochonilhas', 'Ácaros'],
      initialDiseases: ['Fungos', 'Vírus'],
      initialIrrigation: false,
      progressHistory: [
        'Aplicação de inseticidas para controle de cochonilhas - Pragas reduzidas',
        'Uso de acaricidas para controle de ácaros - Pragas controladas',
        'Aplicação de fungicidas para controle de fungos - Fungos controlados',
        'Implementação de estratégias de manejo integrado para controle de vírus - Doenças controladas',
      ],
      imageUrl: 'assets/images/plantacao_feijao.jpg',
    ),
    HistoryModel(
      farmName: 'Fazenda de Tomate',
      farmId: '7',
      culture: 'Tomate',
      initialPests: ['Pulgões', 'Lagartas'],
      initialDiseases: ['Fungos', 'Bactérias'],
      initialIrrigation: true,
      progressHistory: [
        'Aplicação de inseticidas para controle de pulgões - Pragas reduzidas',
        'Aplicação de inseticidas para controle de lagartas - Pragas controladas',
        'Aplicação de fungicidas para controle de fungos - Fungos controlados',
        'Tratamento bactericida para combater as bactérias - Bactérias sob controle',
        'Verificação e manutenção regular do sistema de irrigação - Irrigação estável',
      ],
      imageUrl: 'assets/images/plantacao_tomate.jpg',
    ),
    HistoryModel(
      farmName: 'Fazenda de batata',
      farmId: '8',
      culture: 'Batata',
      initialPests: ['Broca', 'Fungos'],
      initialDiseases: ['Bactérias'],
      initialIrrigation: false,
      progressHistory: [
        'Aplicação de inseticidas para controle de broca - Pragas reduzidas',
        'Aplicação de fungicidas para controle de fungos - Fungos controlados',
        'Monitoramento contínuo das bactérias - Bactérias sob controle',
      ],
      imageUrl: 'assets/images/plantacao_batata.jpg',
    ),
    HistoryModel(
      farmName: 'Fazenda de Cebola',
      farmId: '9',
      culture: 'Cebola',
      initialPests: ['Cochonilhas', 'Ácaros'],
      initialDiseases: ['Fungos', 'Vírus'],
      initialIrrigation: true,
      progressHistory: [
        'Aplicação de inseticidas para controle de cochonilhas - Pragas reduzidas',
        'Uso de acaricidas para controle de ácaros - Pragas controladas',
        'Aplicação de fungicidas para controle de fungos - Fungos controlados',
        'Implementação de estratégias de manejo integrado para controle de vírus - Doenças controladas',
        'Verificação e manutenção regular do sistema de irrigação - Irrigação estável',
      ],
      imageUrl: 'assets/images/plantacao_cebola.jpg',
    ),
    HistoryModel(
      farmName: 'Fazenda de Morango',
      farmId: '10',
      culture: 'Morango',
      initialPests: ['Pulgões', 'Lagartas'],
      initialDiseases: ['Fungos', 'Vírus', 'Bactérias'],
      initialIrrigation: true,
      progressHistory: [
        'Aplicação de inseticidas para controle de pulgões - Pragas reduzidas',
        'Aplicação de inseticidas para controle de lagartas - Pragas controladas',
        'Aplicação de fungicidas para controle de fungos - Fungos controlados',
        'Tratamento antiviral para combater os vírus - Doenças controladas',
        'Tratamento bactericida para combater as bactérias - Bactérias sob controle',
        'Verificação e manutenção regular do sistema de irrigação - Irrigação estável',
      ],
      imageUrl: 'assets/images/plantacao_morango.jpg',
    ),
  ];
}
